app/Http/routes.php
<?php
use App\Faq;
use App\Slider;
use \App\User;
use Illuminate\Support\Facades\Config;

/*
 *
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => 'web'], function () {
    Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);
    Route::get('/home', function () {
        return view('welcome');
    });
    Route::get('/', 'PagesController@welcome');
    Route::get('/how-it-works', function () {
        return view('how-it-works');
    });
    Route::get('/services', function () {
        return view('services');
    });
    Route::get('/contact', function () {
        return view('contact');
    });
    Route::get('/privacy-policy', function (){
        return view('privacy');
    });
    Route::get('/terms-and-conditions', function (){
        return view('terms');
    });
    Route::get('/faq', function (){
        $faqs = Faq::allOrdered();
        return view('faq', compact('faqs'));
    });
    Route::get('/about', function (){
        return view('about');
    });

    Route::get('/calculator', function () {
        $user = Auth::user();
        return view('calculator', compact('user'));
    });

    Route::post('/calculate', 'PagesController@calculate');
    Route::post('/contact','PagesController@sendContactEmail');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware' => 'web', 'auth'], function () {

    Route::auth();

    Route::get('account/subscribe', 'AccountController@subscribe');
    Route::patch('account/subscribe/{user}', 'UserController@resubscribe');
    Route::get('invoice/{invoice}', 'AccountController@showInvoice');

    Route::get('/email',function(){

        $user = User::find('110');
        $order = $user->orders()->first();

        \Mail::send('emails.welcome',['user'=>$user],function($m){
            $m->from(\Config::get('mail.from.address'), trans('general.site_name')) ;
            $m->to('info@postshipper.com', 'PostshipperAdmin')->subject('PostShipper Admin - Order has been paid for');
        });
        \Mail::send('emails.shipped',compact('user','order'),function($m){
            $m->from(\Config::get('mail.from.address'), trans('general.site_name')) ;
            $m->to('info@postshipper.com', 'PostshipperAdmin')->subject('PostShipper Admin - Order has been paid for');
        });
        \Mail::send('emails.consolidated', compact('user','order'),function($m){
            $m->from(\Config::get('mail.from.address'), trans('general.site_name')) ;
            $m->to('info@postshipper.com', 'PostshipperAdmin')->subject('PostShipper Admin - Order has been paid for');
        });



    } );


    Route::group(['prefix' => 'account', 'middleware' => ['auth', 'user']], function () {
        Route::get('/', 'AccountController@index');
        Route::get('/orders', 'AccountController@orders');
        Route::get('/info', 'AccountController@info');
        Route::get('invoice', 'AccountController@invoice');

        //User editing
        Route::get('edit', 'AccountController@show');
        Route::get('edit/billing', 'AccountController@showBilling');
        Route::get('edit/password', 'AccountController@showPassword');

        Route::patch('update/{user}', 'AccountController@update');
        Route::patch('update/password/{user}', 'AccountController@updatePassword');
        Route::patch('update/billing/{user}', 'AccountController@updateBilling');

        //Handling orders
        Route::post('order/{order}', 'OrderController@pay');
        Route::get('order/{order}', 'OrderController@showAccount');
        Route::get('order/{order}/track', 'OrderController@track');
        Route::delete('order/{order}', 'OrderController@destroy');

        //Handling Packages
        Route::get('{package}/resolve', 'PackageController@resolve');
        Route::patch('package/{package}', 'PackageController@updateResolve');

    });
});

//Admin only!
Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'admin'], function () {

    Route::get('/', function () {
        return view('admin.index');
    });

    Route::resource('package', 'PackageController');
    Route::get('order/{order}/process', 'OrderController@process');
    Route::patch('order/updateProcess/{order}', 'OrderController@updateProcess');
    Route::get('order/unprocessed', 'OrderController@viewUnprocessed');
    Route::resource('order', 'OrderController');


    Route::get('user/{user}/edit', 'UserController@edit');
    Route::get('user/{user}/edit/billing', 'UserController@editBilling');
    Route::get('user/{user}/edit/password', 'UserController@editPassword');

    Route::patch('user/update/{user}', 'AccountController@update');
    Route::patch('user/update/password/{user}', 'AccountController@updatePassword');
    Route::patch('user/update/billing/{user}', 'AccountController@updateBilling');

    Route::resource('user', 'UserController');

    Route::get('shipment/{shipment}/track', 'ShipmentController@track');
    Route::post('shipment/{shipment}/complete', 'ShipmentController@complete');
    Route::post('shipment/{shipment}/uncomplete', 'ShipmentController@uncomplete');

    Route::resource('shipment', 'ShipmentController');
    Route::resource('slider', 'SliderController');
    Route::resource('faq', 'FaqController');
    Route::post('faq/{faq}/up', 'FaqController@moveUp');
    Route::post('faq/{faq}/down', 'FaqController@moveDown');

    Route::resource('provider', 'ShippingProviderController');

    Route::resource('tracking', 'TrackingController');

    Route::resource('shipping-box', 'ShippingBoxController');
});

app/Package.php
<?php

namespace App;

use App\Http\Utilities\ShippingCalculations;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Image;
use Laravel\Cashier\Cashier;

class Package extends Model
{
    protected $fillable = [
        'name', 'price', 'open_image', 'close_image', 'user_id', 'received_at', 'weight', 'length', 'height', 'width'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     *
     */
    protected $dates = ['created_at', 'updated_at', 'received_at'];

    public function setReceivedDateAttribute($date)
    {
        $this->attributes['received_at'] = Carbon::parse($date);
    }

    public function scopeUnready($query)
    {
        return $query->whereIn('status', ['resolve', 'pending'])->orderBy('received_at', 'desc');
    }

    public function getDimensionsAttribute()
    {
        return $this->length . '" x ' . $this->width . '" x ' . $this->height . '"';
    }

    public function getOverSizedAttribute()
    {
        //If any measurement is > 20
        if ($this->length > 20 || $this->height > 20 || $this->width > 20) {
            return true;
        }
        //If any two measurements are greater than 16
        if (
            $this->length + $this->height > 32 ||
            $this->width + $this->height > 32 ||
            $this->length + $this->width > 32
        ) {
            return true;
        }
        return false;
    }

    public function getOpenImageAttribute($open_image)
    {
        if ($this->getOriginal('open_image')) {
            return '/uploads/' . $open_image;
        }
        return '/images/icons/deliver.svg';
    }

    public function getOpenCardAttribute()
    {
        if ($this->getOriginal('open_image')) {
            return '/uploads/card/' . $this->getOriginal('open_image');
        }
        return '/images/icons/deliver.svg';
    }

    public function getOpenThumbnailAttribute()
    {
        if ($this->getOriginal('open_image')) {
            return '/uploads/thumbnail/' . $this->getOriginal('open_image');
        }
        return '/images/icons/deliver.svg';
    }

    public function getCloseImageAttribute($photo)
    {
        if ($this->getOriginal('close_image')) {
            return '/uploads/' . $photo;
        }
        return '/images/icons/deliver.svg';
    }

    public function getCloseCardAttribute()
    {
        if ($this->getOriginal('close_image')) {
            return '/uploads/card/' . $this->getOriginal('close_image');
        }
        return '/images/icons/deliver.svg';
    }

    public function getCloseThumbnailAttribute()
    {
        if ($this->getOriginal('close_image')) {
            return '/uploads/thumbnail/' . $this->getOriginal('close_image');
        }
        return '/images/icons/deliver.svg';
    }


    public function getReceivedDateAttribute($date)
    {
        return $date;
    }

    public function getPriceOgAttribute()
    {
        return $this->attributes['price'];
    }

    public function getPriceAttribute($price)
    {
        return Cashier::formatAmount($price);
    }


    public function getWeightOgAttribute()
    {
        return $this->attributes['weight'];
    }

    public function getWeightAttribute($weight)
    {
        return ShippingCalculations::gramsToPounds($weight) . ' LB';
    }

    public function setWeightAttribute($weight)
    {
        $this->attributes['weight'] = ShippingCalculations::poundsToGrams($weight);
    }

    public function getDaysLeftAttribute()
    {
        $left = 45 - Carbon::parse($this->attributes['received_at'])->diffInDays();
        if ($left <= 0) {
            return false;
        }
        return $left;
    }

    public function setPriceAttribute($price)
    {
        $this->attributes['price'] = ceil($price * 100);
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function order()
    {
        return $this->belongsTo('App\Order');
    }
}

app/Http/Controllers/PackageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdatePackagePriceRequest;
use App\Http\Requests\UpdatePackageRequest;
use App\Http\Utilities\ImageHandler;
use App\Http\Utilities\ShippingCalculations;
use App\Order;
use Carbon\Carbon;
use Illuminate\Support\Facades\Session;
use Yajra\Datatables\Services\DataTable;
use Yajra\Datatables\Datatables;
use App\Http\Requests\CreateAuthRequest;
use App\Http\Requests\CreatePackageRequest;
use App\Http\Requests\resolvePackageIssue;
use App\Package;
use App\User;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class PackageController extends Controller
{
    public function index()
    {
        $packages = Package::all();

        return view('admin.package.index', compact('packages'));
    }

    public function show($id)
    {

        $package = Package::findOrFail($id);

        return view('admin.package.show', compact('package'));
    }


    public function create()
    {
        return view('admin.package.create');
    }

    public function store(CreatePackageRequest $request)
    {
        //Mass Assign
        $package = Package::create($request->except('weight'));

        $package->status = $request->price == 0 ? 'resolve' : 'pending';
        $package->weight = $request->weight;

        //HAndle the image saving
        $image = $request->open_image;
        $filename = 'package-open-' . time() . '.' . $image->getClientOriginalExtension();
        ImageHandler::storeImage($image, $filename);
        $package->open_image = $filename;

        $image = $request->close_image;
        $filename = 'package-close-' . time() . '.' . $image->getClientOriginalExtension();
        ImageHandler::storeImage($image, $filename);
        $package->close_image = $filename;

        //Get an open order or create it
        $order = $package->user->orders()->whereIn('status', ['pending', 'consolidated'])->firstOrCreate([
            'user_id' => $package->user_id,
        ]);
        //Reset the order Status
        $order->update([
            'status' => 'pending',
            'consolidated_at' => Carbon::now()
        ]);

        //Attach the package to the order
        $package->order()->associate($order);
        $package->save();

        \Session::flash('flash_message', "Package has been created");
        return redirect()->action('OrderController@process', $order);
    }

    public function edit(Package $package)
    {

        return view('admin.package.edit', compact('package'));
    }

    public function update(Package $package, UpdatePackageRequest $request)
    {
        //Only do this update if the package is unused
        if (in_array($package->status, ['pending', 'resolve'])) {
            if ($request->price) {
                $package->status = 'pending';
            } else {
                $package->status = 'resolve';
            }
        }
        $package->update($request->except('open_image','close_image'));

        if ($request->open_image) {
            //HAndle the image saving
            $image = $request->open_image;
            $filename = 'package-open-' . time() . '.' . $image->getClientOriginalExtension();
            ImageHandler::storeImage($image, $filename);
            $package->open_image = $filename;
        }

        if ($request->close_image) {

            $image = $request->close_image;
            $filename = 'package-close-' . time() . '.' . $image->getClientOriginalExtension();
            ImageHandler::storeImage($image, $filename);
            $package->close_image = $filename;
        }

        $package->save();

        \Session::flash('flash_message', 'Package Updated');
        return redirect()->action('PackageController@show', $package);
    }

    public function updateResolve(UpdatePackagePriceRequest $request, Package $package)
    {
        $package->status = 'pending';

        $old_price = $package->price;

        $package->price = $request->price;
        $package->save();
        \Session::flash('flash_message', trans('account.flash_update_package'));

        \Mail::send('emails.admin.package-price', ['package' => $package, 'old_price' => $old_price], function ($m) {
            $m->from(\Config::get('mail.from.address'), trans('general.site_name'));
            $m->to('info@postshipper.com', 'PostshipperAdmin')->subject('PostShipper Admin - Package Price Changed');
        });

        return redirect('account');
    }

    public function resolve(Package $package)
    {
        $user = Auth::user();
        return view('account.package.resolve', compact('package'), compact('user'));
    }

    public function destroy(Package $package)
    {
        $order = $package->order;
        $package->delete();

        /*
         * If the order is now empty
         * we'll need to delete it
         */
        if ($order->packages->isEmpty()) {
            $order->delete();
        }

        Session::flash('flash_message', 'Package deleted');
        return redirect()->action('PackageController@index');
    }
}

resources/views/partials/package/package-display.blade.php
<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="thumbnail package package-{{$package->status}}">
        <ul class="nav nav-tabs">
            <li role="presentation" class="col-sm-6 active package-tabs"><a href="#open_{{$package->id}}" role="tab"
                                                                            class="open-box"
                                                                            data-toggle="tab"></a></li>
            <li role="presentation" class="col-sm-6 package-tabs"><a href="#close_{{$package->id}}" role="tab"
                                                                     data-toggle="tab"
                                                                     class="closed-box"></a>
            </li>
        </ul>
        <div class="tab-content">
            <a href="{{ $package->open_image }}" target="_blank" class="tab-pane active fade in" id="open_{{$package->id}}" >
                <img  src="{{ $package->open_card }}">
            </a>
            <a href="{{ $package->close_image }}" target="_blank" class="tab-pane fade" id="close_{{$package->id}}">
                <img   src="{{ $package->close_card }}">
            </a>
        </div>

        <div class="caption">
            <h4>{{ $package->name }}</h4>
            <ul class="list-unstyled">
                <li>{{Lang::get('account.package_id')}} {{ $package->id }}</li>
                <li>{{Lang::get('account.package_weight')}} <span class="force_ltr">{{ $package->weight }}</span></li>
                <li>{{Lang::get('account.package_dimensions')}} <span class="force_ltr">{{ $package->dimensions }}</span></li>
                @if($package->days_left)
                    <li>{{Lang::get('account.package_arrived', ['days' => $package->days_left] )}} </li>
                @else
                    <li class="text-danger">{{ Lang::get('account.package_overdue') }}</li>
                @endif
                @if($package->status == 'resolve')
                    <li>
                        <a href="account/{{$package->id}}/resolve"
                           data-featherlight-namespace="resolve-popup"
                           data-featherlight="ajax"
                           class="btn btn-warning" role="button">{{ Lang::get('account.package_resolve') }}</a>
                    </li>
                @else
                    <li>{{Lang::get('account.package_value')}} <span dir="ltr">{{ $package->price }}</span>
                        @if(in_array($package->order->status, ['pending','consolidated']))
                            <a class="edit" href="{{ url("account/$package->id/resolve") }}"
                               data-featherlight-namespace="resolve-popup"
                               data-featherlight="ajax"
                            ><i class="fa fa-pencil-square-o"></i></a>
                        @endif
                    </li>
                @endif
            </ul>
        </div>
    </div>
</div>

resources/views/partials/package/package-tables.blade.php
<table id="packages" class="table table-striped table-condensed table-responsive table-hover datatable">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Price</th>
        <th>Status</th>
        <th>Dimensions(LWH)</th>
        <th>Oversized</th>
        <th>Weight</th>
        <th>Received Date</th>
        <th>Destination</th>
        <th>Days In Warehouse</th>
        <th>User</th>
        <th>Mailbox</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>

    @foreach ($packages as $package)
        <tr>
            <td>{{  $package->id }}</td>
            <td>{{ $package->name }}</td>
            <td>{{ $package->price }}</td>
            <td>{{ $package->status }}</td>
            <td>{{ $package->dimensions }}</td>
            <td>@if($package->oversized) <span class="text-danger">Yes</span> @else  No @endif</td>
            <td>{{ $package->weight }}</td>
            <td>{{ $package->received_at->toDayDateTimeString() }}</td>
            <td>{{ Countries::getOne($package->user->country) }}</td>
                @if( $package->received_at->diffInDays() >= 45 && in_array($package->status, ['resolve','pending']) )
                <td class="text-danger">
                  {{ $package->received_at->diffInDays() }}
                @elseif( !in_array($package->status, ['resolve','pending']) )
                <td> -
                @else
                <td>{{ $package->received_at->diffInDays() }}
                @endif
            </td>
            <td><a href="{{ action('UserController@show',$package->user) }}">{{ $package->user->fullName }}</a></td>
            <td><a href="{{ action('UserController@show',$package->user) }}">{{ $package->user->id }}</a></td>
            <td width="120px"><a href="{{ url("admin/package/$package->id") }}">
                    <button class="btn btn-success">View</button>
                </a>
                <a href="{{ url("admin/package/$package->id/edit") }}">
                    <button class="btn btn-primary">Edit</button>
                </a></td>
        </tr>
    @endforeach
    </tbody>
</table>