app/Http/routes.php
<?php
use App\Faq;
use App\Slider;
use \App\User;
use Illuminate\Support\Facades\Config;

/*
 *
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => 'web'], function () {
    Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);
    Route::get('/home', function () {
        return view('welcome');
    });
    Route::get('/', 'PagesController@welcome');
    Route::get('/how-it-works', function () {
        return view('how-it-works');
    });
    Route::get('/services', function () {
        return view('services');
    });
    Route::get('/contact', function () {
        return view('contact');
    });
    Route::get('/privacy-policy', function (){
        return view('privacy');
    });
    Route::get('/terms-and-conditions', function (){
        return view('terms');
    });
    Route::get('/faq', function (){
        $faqs = Faq::allOrdered();
        return view('faq', compact('faqs'));
    });
    Route::get('/about', function (){
        return view('about');
    });

    Route::get('/calculator', function () {
        $user = Auth::user();
        return view('calculator', compact('user'));
    });

    Route::post('/calculate', 'PagesController@calculate');
    Route::post('/contact','PagesController@sendContactEmail');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware' => 'web', 'auth'], function () {

    Route::auth();

    Route::get('account/subscribe', 'AccountController@subscribe');
    Route::patch('account/subscribe/{user}', 'UserController@resubscribe');
    Route::get('invoice/{invoice}', 'AccountController@showInvoice');

    Route::get('/email',function(){

        $user = User::find('110');
        $order = $user->orders()->first();

        \Mail::send('emails.welcome',['user'=>$user],function($m){
            $m->from(\Config::get('mail.from.address'), trans('general.site_name')) ;
            $m->to('info@postshipper.com', 'PostshipperAdmin')->subject('PostShipper Admin - Order has been paid for');
        });
        \Mail::send('emails.shipped',compact('user','order'),function($m){
            $m->from(\Config::get('mail.from.address'), trans('general.site_name')) ;
            $m->to('info@postshipper.com', 'PostshipperAdmin')->subject('PostShipper Admin - Order has been paid for');
        });
        \Mail::send('emails.consolidated', compact('user','order'),function($m){
            $m->from(\Config::get('mail.from.address'), trans('general.site_name')) ;
            $m->to('info@postshipper.com', 'PostshipperAdmin')->subject('PostShipper Admin - Order has been paid for');
        });



    } );


    Route::group(['prefix' => 'account', 'middleware' => ['auth', 'user']], function () {
        Route::get('/', 'AccountController@index');
        Route::get('/orders', 'AccountController@orders');
        Route::get('/info', 'AccountController@info');
        Route::get('invoice', 'AccountController@invoice');

        //User editing
        Route::get('edit', 'AccountController@show');
        Route::get('edit/billing', 'AccountController@showBilling');
        Route::get('edit/password', 'AccountController@showPassword');

        Route::patch('update/{user}', 'AccountController@update');
        Route::patch('update/password/{user}', 'AccountController@updatePassword');
        Route::patch('update/billing/{user}', 'AccountController@updateBilling');

        //Handling orders
        Route::post('order/{order}', 'OrderController@pay');
        Route::get('order/{order}', 'OrderController@showAccount');
        Route::get('order/{order}/track', 'OrderController@track');
        Route::delete('order/{order}', 'OrderController@destroy');

        //Handling Packages
        Route::get('{package}/resolve', 'PackageController@resolve');
        Route::patch('package/{package}', 'PackageController@updateResolve');

    });
});

//Admin only!
Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'admin'], function () {

    Route::get('/', function () {
        return view('admin.index');
    });

    Route::resource('package', 'PackageController');
    Route::get('order/{order}/process', 'OrderController@process');
    Route::patch('order/updateProcess/{order}', 'OrderController@updateProcess');
    Route::get('order/unprocessed', 'OrderController@viewUnprocessed');
    Route::resource('order', 'OrderController');


    Route::get('user/{user}/edit', 'UserController@edit');
    Route::get('user/{user}/edit/billing', 'UserController@editBilling');
    Route::get('user/{user}/edit/password', 'UserController@editPassword');

    Route::patch('user/update/{user}', 'AccountController@update');
    Route::patch('user/update/password/{user}', 'AccountController@updatePassword');
    Route::patch('user/update/billing/{user}', 'AccountController@updateBilling');

    Route::resource('user', 'UserController');

    Route::get('shipment/{shipment}/track', 'ShipmentController@track');
    Route::post('shipment/{shipment}/complete', 'ShipmentController@complete');
    Route::post('shipment/{shipment}/uncomplete', 'ShipmentController@uncomplete');

    Route::resource('shipment', 'ShipmentController');
    Route::resource('slider', 'SliderController');
    Route::resource('faq', 'FaqController');
    Route::post('faq/{faq}/up', 'FaqController@moveUp');
    Route::post('faq/{faq}/down', 'FaqController@moveDown');

    Route::resource('provider', 'ShippingProviderController');

    Route::resource('tracking', 'TrackingController');

    Route::resource('shipping-box', 'ShippingBoxController');
});

app/Order.php
<?php

namespace App;

use App\Http\Utilities\ShippingCalculations;
use Illuminate\Database\Eloquent\Model;
use Laravel\Cashier\Cashier;

class Order extends Model
{
    //

    protected $fillable = [
        'name', 'slow_price', 'fast_price', 'box_option', 'photo', 'status'
        , 'user_id', 'cost', 'shipping_method', 'charge_id','ordered_at'
        ,'consolidated_at', 'length', 'width', 'height', 'weight'
    ];

    protected $casts = [
        'box_option' => 'boolean'
    ];

    protected $dates = [
        'received_at', 'created_at', 'updated_at', 'ordered_at', 'consolidated_at'
    ];

    public function scopeNotCompleted($query)
    {
        return $query->where('status', '!=', 'complete');
    }

    public function scopeReady($query)
    {
        return $query->where('status', 'ready')
            ->orderBy('shipping_method', 'asc')
            ->orderBy('id', 'asc');
    }

    public function scopeUnshipped($query)
    {
        return $query->whereIn('status', ['pending', 'consolidated']);
    }

    public function scopePaid($query)
    {
        return $query->whereNotIn('status', ['pending', 'consolidated']);
    }

    public function getStatusFormatAttribute(){
        switch($this->original['status']){
            case 'pending':
                return trans('account.pending');
                break;
            case 'consolidated':
                return trans('account.consolidated');
                break;
            case 'ready':
                return trans('account.ready');
                break;
            case 'shipped':
                return trans('account.shipped');
                break;
            case 'arrived':
                return trans('account.arrived');
                break;
            case 'delivered':
                return trans('account.delivered');
                break;
        }
    }

    public function getSlowPriceAttribute($price)
    {
        return Cashier::formatAmount($price);
    }

    public function getFastPriceAttribute($price)
    {
        return Cashier::formatAmount($price);
    }

    public function setSlowPriceAttribute($price)
    {
        $this->attributes['slow_price'] = round($price, 2) * 100;
    }

    public function setFastPriceAttribute($price)
    {
        $this->attributes['fast_price'] = round($price, 2) * 100;
    }

    public function getWeightAttribute()
    {
        if(empty($this->attributes['weight'])) {
            $weight = 0;
            foreach ($this->packages()->get() as $package) {
                $weight += $package->getOriginal('weight');
            }
        } else $weight = $this->attributes['weight'];
        return ShippingCalculations::gramsToPounds($weight);
    }
    public function getPoundsAttribute(){
        return $this->getWeightAttribute();
    }

    public function getShippingMethodAttribute($shipping_method){
        switch($shipping_method){
            case 'box':
                return trans('general.box');
            break;
            case 'slow':
                return trans('general.slow');
                break;
            case 'fast':
                return trans('general.fast');
                break;
        }

        return $shipping_method;

    }

    public function calculateCost($shipping_method)
    {
        switch ($shipping_method) {
            case 'fast' :
                return $this->getOriginal('fast_price');
                break;
            case 'slow' :
                return $this->getOriginal('slow_price');
                break;
            case 'box' :
                //Find the hd box box
                return ShippingBox::find(1)->getOriginal('price');
                break;
        }
    }

    public function getPhotoAttribute()
    {
        if ($this->getOriginal('consolidated_image')) {
            return '/uploads/' . $this->getOriginal('consolidated_image');
        }

        return '/images/package_pending.png';
    }

    public function getCardAttribute()
    {
        if ($this->getOriginal('consolidated_image')) {
            return '/uploads/card/' . $this->getOriginal('consolidated_image');
        }
        return '/images/package_pending.png';
    }

    public function getThumbnailAttribute()
    {
        if ($this->getOriginal('consolidated_image')) {
            return '/uploads/thumbnail/' . $this->getOriginal('consolidated_image');
        }
        return '/images/package_pending.png';
    }

    public function getCostOGAttribute()
    {
        return $this->attributes['cost'];
    }
    public function getCostAttribute($cost)
    {
        if (!$cost) {
            Return 'Unpaid';
        }
        return Cashier::formatAmount($cost);
    }


    public function packages()
    {
        return $this->hasMany('App\Package');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function tracking()
    {
        return $this->morphMany('App\Tracking', 'trackable');
    }

    public function shipment()
    {
        return $this->belongsTo('App\Shipment');
    }
}

app/Package.php
<?php

namespace App;

use App\Http\Utilities\ShippingCalculations;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Image;
use Laravel\Cashier\Cashier;

class Package extends Model
{
    protected $fillable = [
        'name', 'price', 'open_image', 'close_image', 'user_id', 'received_at', 'weight', 'length', 'height', 'width'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     *
     */
    protected $dates = ['created_at', 'updated_at', 'received_at'];

    public function setReceivedDateAttribute($date)
    {
        $this->attributes['received_at'] = Carbon::parse($date);
    }

    public function scopeUnready($query)
    {
        return $query->whereIn('status', ['resolve', 'pending'])->orderBy('received_at', 'desc');
    }

    public function getDimensionsAttribute()
    {
        return $this->length . '" x ' . $this->width . '" x ' . $this->height . '"';
    }

    public function getOverSizedAttribute()
    {
        //If any measurement is > 20
        if ($this->length > 20 || $this->height > 20 || $this->width > 20) {
            return true;
        }
        //If any two measurements are greater than 16
        if (
            $this->length + $this->height > 32 ||
            $this->width + $this->height > 32 ||
            $this->length + $this->width > 32
        ) {
            return true;
        }
        return false;
    }

    public function getOpenImageAttribute($open_image)
    {
        if ($this->getOriginal('open_image')) {
            return '/uploads/' . $open_image;
        }
        return '/images/icons/deliver.svg';
    }

    public function getOpenCardAttribute()
    {
        if ($this->getOriginal('open_image')) {
            return '/uploads/card/' . $this->getOriginal('open_image');
        }
        return '/images/icons/deliver.svg';
    }

    public function getOpenThumbnailAttribute()
    {
        if ($this->getOriginal('open_image')) {
            return '/uploads/thumbnail/' . $this->getOriginal('open_image');
        }
        return '/images/icons/deliver.svg';
    }

    public function getCloseImageAttribute($photo)
    {
        if ($this->getOriginal('close_image')) {
            return '/uploads/' . $photo;
        }
        return '/images/icons/deliver.svg';
    }

    public function getCloseCardAttribute()
    {
        if ($this->getOriginal('close_image')) {
            return '/uploads/card/' . $this->getOriginal('close_image');
        }
        return '/images/icons/deliver.svg';
    }

    public function getCloseThumbnailAttribute()
    {
        if ($this->getOriginal('close_image')) {
            return '/uploads/thumbnail/' . $this->getOriginal('close_image');
        }
        return '/images/icons/deliver.svg';
    }


    public function getReceivedDateAttribute($date)
    {
        return $date;
    }

    public function getPriceOgAttribute()
    {
        return $this->attributes['price'];
    }

    public function getPriceAttribute($price)
    {
        return Cashier::formatAmount($price);
    }


    public function getWeightOgAttribute()
    {
        return $this->attributes['weight'];
    }

    public function getWeightAttribute($weight)
    {
        return ShippingCalculations::gramsToPounds($weight) . ' LB';
    }

    public function setWeightAttribute($weight)
    {
        $this->attributes['weight'] = ShippingCalculations::poundsToGrams($weight);
    }

    public function getDaysLeftAttribute()
    {
        $left = 45 - Carbon::parse($this->attributes['received_at'])->diffInDays();
        if ($left <= 0) {
            return false;
        }
        return $left;
    }

    public function setPriceAttribute($price)
    {
        $this->attributes['price'] = ceil($price * 100);
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function order()
    {
        return $this->belongsTo('App\Order');
    }
}

resources/views/partials/order/order-display.blade.php
<div class="col-sm-12 order-details">
    <div class="panel panel-default">
        <div class="panel-heading ">
            <div class="row order-display-heading">
                <div class="col-sm-3 col-xs-6">
                    <h5>{{ Lang::get('account.order_id') }}</h5>
                    <span>{{ $order->id }}</span>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <h5>{{ Lang::get('account.shipped_at') }}</h5>
                    <span>{{ $order->ordered_at->toFormattedDateString() }}</span>
                </div>

                <div class="col-sm-3 col-xs-6">
                    <h5>{{ Lang::get('account.order_cost') }}</h5>
                    <span>{{ $order->cost }}</span>
                </div>

                <div class="col-sm-3 col-xs-6">
                    <h5>{{ Lang::get('account.package_count') }}</h5>
                    <span>{{ count($order->packages) }}</span>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">

                <div class="col-sm-3 col-sm-offset-0 col-xs-10 col-xs-offset-1 order-display-image">
                    <div>
                        <a href="{{ $order->photo }}" data-featherlight="image">
                            <img src="{{ $order->card }}" class="thumbnail col-xs-offset-1 col-xs-10 col-sm-3">
                        </a>
                    </div>
                </div>

                <div class="col-sm-4 col-xs-10 col-xs-offset-1 col-sm-offset-0">
                    <div class="row">
                        @foreach($order->packages as $package)
                            <div class="col-xs-4">
                                <a href="{{ $package->open_image }}" data-featherlight="image">
                                    <img class="micro thumbnail" src="{{ $package->open_card }}">
                                </a>
                            </div>
                        @endforeach
                    </div>
                </div>

                <div class="col-sm-5 col-xs-10 col-xs-offset-1 col-sm-offset-0">
                    <ul class="list-unstyled">
                        <li>{{ trans('account.order_status') }}: <span> {{ $order->status_format }}</span></li>
                        <li>{{ trans('account.order_weight') }}: <span> {{ ShippingCalculations::gramsToPounds($order->packages->sum('weight_og')) }}
                                lbs </span>
                        </li>
                        <li>{{ trans('account.customs_value') }}:
                            <span dir="ltr">{{ Laravel\Cashier\Cashier::formatAmount($order->packages->sum('price_og')) }}</span>
                        </li>
                        <li>{{ trans('account.shipping_method') }}: <span>{{ $order->shipping_method }}</span></li>
                    </ul>
                </div>
                <div class="col-sm-12">
                    <a class="order-buttons" href="{{ action('OrderController@showAccount',$order) }}">
                        <button class="btn btn-success">{{ Lang::get('account.view_order') }}</button>
                    </a>
                    <a class="order-buttons" href="{{ action('OrderController@track',$order) }}">
                        <button class="btn btn-success">{{ Lang::get('account.track_order') }}</button>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="progress">
                        @if($order->status == 'pending')
                            <div class="progress-bar" role="progressbar" aria-valuenow="30"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 20%;">
                                {{Lang::get('account.statusbar_pending')}}
                            </div>
                        @elseif($order->status == 'consolidated')
                            <div class="progress-bar" role="progressbar" aria-valuenow="40"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 40%;">
                                {{Lang::get('account.statusbar_consolidated')}}
                            </div>
                        @elseif($order->status == 'ready')
                            <div class="progress-bar" role="progressbar" aria-valuenow="40"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 40%;">
                                {{Lang::get('account.statusbar_ready')}}
                            </div>
                        @elseif($order->status == 'shipped')
                            <div class="progress-bar" role="progressbar" aria-valuenow="60"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                {{Lang::get('account.statusbar_shipped')}}
                            </div>
                        @elseif($order->status == 'arrived')
                            <div class="progress-bar" role="progressbar" aria-valuenow="80"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
                                {{Lang::get('account.statusbar_arrived')}}
                            </div>
                        @else
                            <div class="progress-bar" role="progressbar" aria-valuenow="100"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                {{Lang::get('account.statusbar_delivered')}}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/order/order-tables.blade.php
<div class="table-responsive" xmlns="http://www.w3.org/1999/html">
    <table id="orders" class="table table-striped ">
        <thead>
        <tr>
            <th>#</th>
            <th>Box ID</th>
            <th>User</th>
            <th>Status</th>
            <th>Package Count</th>
            <th>Date Created</th>
            <th>Date Readied</th>
            <th>Gross Paid</th>
            <th>Destination</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </tfoot>
        <tbody>

        @foreach ($orders as $order)
            <tr>
                <td>{{ $order->id }}</td>
                <td>{{ $order->user->id }}</td>
                <td><a href='{{ url("admin/user/show/$order->user->id") }}'>{{ $order->user->fullName }}</a></td>
                <td>{{ $order->status }}</td>
                <td>{{ count($order->packages) }}</td>
                <td>{{ $order->created_at->toFormattedDateString() }}</td>
                @if($order->ordered_at)
                    <td>{{ $order->ordered_at->toFormattedDateString() }}</td>
                @else
                    <td>Not Ready to ship</td>
                @endif
                <td>{{ $order->cost }}</td>
                @if($order->user->country == 'kw')
                  <td style="color:blue;">{{ Countries::getOne($order->user->country) }}</td>
                @else
                  <td>{{ Countries::getOne($order->user->country) }}</td>
                @endif
                <td>
                    <a href='{{ url("admin/order/$order->id") }}' ><button class="btn btn-success">View</button></a>
                    @if($order->status == 'pending' || $order->status == 'consolidated')
                        <a href='{{ url("admin/order/$order->id/process") }}'>
                            <button class="btn btn-primary"> Consolidate</button>
                        </a>
                    @else
                        <a target="_blank" href='{{ action('AccountController@showInvoice', $order->id) }}' >
                            <button class="btn btn-primary">Invoice</button></a>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

@section('footer')
    <script>
        $(document).ready(function () {
            $('#orders').DataTable({
                "footerCallback": function (row, data, start, end, display) {
                    var api = this.api(), data;

                    // Remove the formatting to get integer data for summation
                    var intVal = function (i) {
                        if (i == 'Unpaid') {
                            return 0;
                        }
                        return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '') * 1 :
                                typeof i === 'number' ?
                                        i : 0;
                    };

                    // Total over all pages
                    total = api
                            .column(':contains(Paid)')
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);

                    // Total over this page
                    pageTotal = api
                            .column(':contains(Paid)', {page: 'current'})
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);

                    // Update footer
                    $(api.column(':contains(Paid)').footer()).html(
                            '$' + pageTotal + ' ( $' + total + ' total)'
                    );
                }
            });
        });
    </script>
@endsection

resources/views/partials/order/shipping.blade.php
<address class="shipping-address">
    {{ $user->address }} <br>
    @if($user->address2)
        {{ $user->address2 }}  <br>
    @endif
    {{ $user->city }} , {{ $user->state }} {{ $user->postal }}
    <br>
    {{ Countries::getOne($user->country, 'en', 'cldr') }} <br>
    <abbr title="Phone">P:</abbr> {{ $user->phone }} <br>
</address>